openapi: 3.0.3
info:
  title: Individuals State Benefits (MTD)
  description: "The following endpoints are stateful in the Sandbox:\n\n- [Create\
    \ State Benefit](#/paths/~1individuals~1state-benefits~1%7Bnino%7D~1%7BtaxYear%7D/post)\n\
    - [Amend State Benefit](#/paths/~1individuals~1state-benefits~1%7Bnino%7D~1%7BtaxYear%7D~1%7BbenefitId%7D/put)\n\
    - [Delete State Benefit](#/paths/~1individuals~1state-benefits~1%7Bnino%7D~1%7BtaxYear%7D~1%7BbenefitId%7D/delete)\n\
    - [List State Benefits](#/paths/~1individuals~1state-benefits~1%7Bnino%7D~1%7BtaxYear%7D/get)\n\
    - [Amend State Benefit Amounts](#/paths/~1individuals~1state-benefits~1%7Bnino%7D~1%7BtaxYear%7D~1%7BbenefitId%7D~1amounts/put)\n\
    - [Delete State Benefit Amounts](#/paths/~1individuals~1state-benefits~1%7Bnino%7D~1%7BtaxYear%7D~1%7BbenefitId%7D~1amounts/delete)\n\
    \  \n# Send fraud prevention data\nHMRC monitors transactions to help protect\
    \ your customers' confidential data from criminals and fraudsters. \n\n<div class=\"\
    govuk-warning-text warning-icon-fix\">\n  <span class=\"govuk-warning-text__icon\
    \ warning-icon-ui-fix\" aria-hidden=\"true\">!</span>\n  <strong class=\"govuk-warning-text__text\"\
    >\n    <span class=\"govuk-warning-text__assistive\">Warning</span>\n    You are\
    \ required by law to submit header data for this API. This includes all associated\
    \ APIs and endpoints.\n  </strong>\n</div>\n\n[Check the data you need to send](/guides/fraud-prevention/).\
    \ You can also use the [Test API](/api-documentation/docs/api/service/txm-fph-validator-api/2.0)\
    \ during initial development and as part of your quality assurance checks.\n\n\
    # Mapping APIs to Self Assessment tax return forms\nSome parameters in this API\
    \ map to box numbers in one or more Self Assessment tax return forms. To learn\
    \ more and to download this mapping information as a CSV file, go to [income-tax-mtd-changelog/mapping](https://github.com/hmrc/income-tax-mtd-changelog?tab=readme-ov-file#mapping-apis-to-self-assessment-tax-return-forms)\
    \ on GitHub.\n\n# Changelog\nYou can find the changelog in the [income-tax-mtd-changelog](https://github.com/hmrc/income-tax-mtd-changelog/#readme)\
    \ on GitHub.\n\n# Support\n\n* Direct reports of bugs or errors in Production\
    \ or Sandbox code, or queries about HMRC business functionality (such as how a\
    \ specific field is used by HMRC or why it is needed) to the [Software Development\
    \ Support Team (SDST)](https://developer.service.hmrc.gov.uk/developer/support).\n\
    * Send queries or feedback related to the design of the APIs (including recommended\
    \ changes) using the [income-tax-mtd-changelog](https://github.com/hmrc/income-tax-mtd-changelog/issues)\
    \ GitHub page.\n* <a href=\"/contact/report-technical-problem?newTab=true&service=api-documentation-frontend\"\
    \ target=\"_blank\">Is this page not working properly? (opens in new tab)</a>\n"
  version: "2.0"
servers:
- url: https://test-api.service.hmrc.gov.uk
  description: Sandbox
- url: https://api.service.hmrc.gov.uk
  description: Production
paths:
  /individuals/state-benefits/{nino}/{taxYear}:
    get:
      summary: List State Benefits
      parameters:
      - name: benefitId
        in: query
        description: |
          Unique identifier of the benefit.
        required: false
        schema:
          pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
          type: string
          example: f0d83ac0-a10a-4d57-9e41-6d033832779f
      security:
      - User-Restricted:
        - read:self-assessment
    post:
      summary: Create State Benefit
      security:
      - User-Restricted:
        - write:self-assessment
  /individuals/state-benefits/{nino}/{taxYear}/{benefitId}:
    put:
      summary: Amend State Benefit
      security:
      - User-Restricted:
        - write:self-assessment
    delete:
      summary: Delete State Benefit
      security:
      - User-Restricted:
        - write:self-assessment
  /individuals/state-benefits/{nino}/{taxYear}/{benefitId}/amounts:
    put:
      summary: Amend State Benefit Amounts
      security:
      - User-Restricted:
        - write:self-assessment
    delete:
      summary: Delete State Benefit Amounts
      security:
      - User-Restricted:
        - write:self-assessment
  /individuals/state-benefits/{nino}/{taxYear}/{benefitId}/ignore:
    post:
      summary: Ignore State Benefit
      security:
      - User-Restricted:
        - write:self-assessment
  /individuals/state-benefits/{nino}/{taxYear}/{benefitId}/unignore:
    post:
      summary: Unignore State Benefit
      security:
      - User-Restricted:
        - write:self-assessment
components:
  parameters:
    benefitId:
      name: benefitId
      in: query
      description: |
        Unique identifier of the benefit.
      required: false
      schema:
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
        type: string
        example: f0d83ac0-a10a-4d57-9e41-6d033832779f
  securitySchemes:
    User-Restricted:
      type: oauth2
      description: "HMRC supports OAuth 2.0 for authenticating [User-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints)\
        \ API requests"
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            write:self-assessment: Grant write access
            read:self-assessment: Grant read access
