#!/bin/bash

# Script to help set up GitHub secrets for SMTP configuration

echo "=== GitHub Secrets Setup for SMTP ==="
echo ""
echo "You need to add the RESEND_API_KEY secret to your GitHub repository."
echo ""
echo "Option 1: Using GitHub CLI (recommended)"
echo "----------------------------------------"
echo "1. Get your Resend API key from: https://resend.com/api-keys"
echo "2. Run this command (replace with your actual API key):"
echo ""
echo "   gh secret set RESEND_API_KEY --body \"re_YOUR_API_KEY_HERE\""
echo ""
echo "Option 2: Using GitHub Web UI"
echo "------------------------------"
echo "1. Go to: https://github.com/gocalceum/calc/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo "3. Name: RESEND_API_KEY"
echo "4. Value: Your Resend API key (starts with re_)"
echo "5. Click 'Add secret'"
echo ""
echo "After adding the secret:"
echo "------------------------"
echo "1. The workflow will run automatically on next push"
echo "2. Or manually trigger it:"
echo "   gh workflow run configure-smtp.yml"
echo ""
echo "To verify the secret is set:"
echo "   gh secret list | grep RESEND"
echo ""