name: Configure SMTP

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/configure-smtp.yml'

env:
  PROJECT_ID: ducrwfvylwdaqpwfbdub

jobs:
  configure-smtp:
    name: Configure SMTP Settings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure SMTP via Management API
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: |
          # Configure SMTP settings
          curl -X PATCH "https://api.supabase.com/v1/projects/${{ env.PROJECT_ID }}/config/auth" \
            -H "Authorization: Bearer $SUPABASE_ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "external_email_enabled": true,
              "smtp_host": "smtp.resend.com",
              "smtp_port": 587,
              "smtp_user": "resend",
              "smtp_pass": "'"$RESEND_API_KEY"'",
              "smtp_sender_email": "noreply@calceum.com",
              "smtp_sender_name": "Calceum",
              "smtp_max_frequency": 30,
              "mailer_autoconfirm": false
            }' | jq '.'
          
          echo "✅ SMTP configuration updated"
      
      - name: Verify Configuration
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "Fetching current auth configuration..."
          curl -X GET "https://api.supabase.com/v1/projects/${{ env.PROJECT_ID }}/config/auth" \
            -H "Authorization: Bearer $SUPABASE_ACCESS_TOKEN" \
            | jq '{
              smtp_enabled: .external_email_enabled,
              smtp_host: .smtp_host,
              smtp_port: .smtp_port,
              smtp_user: .smtp_user,
              smtp_sender: .smtp_sender_email,
              smtp_configured: (.smtp_host != null and .smtp_pass != null)
            }'